name: sass
version: 0.5.0
description: >
  Sass-transformer for pub-serve and pub-build.
authors:
  - Juha Komulainen <juha.komulainen@evident.fi>
  - Luis Vargas <luisvargastijerino@gmail.com>
homepage: https://github.com/dart-league/dart-sass
dependencies:
  barback: ^0.15.0
  utf: ^0.9.0
dev_dependencies:
  test: ^0.12.0
