name: sass
version: 0.4.2
description: >
  Sass-transformer for pub-serve and pub-build.
author: Juha Komulainen <juha.komulainen@evident.fi>
homepage: https://github.com/EvidentSolutions/dart-sass
dependencies:
  barback: ">=0.15.0 <0.16.0"
  utf: ">=0.9.0 <0.9.1"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
  mock: ">=0.11.0 <0.12.0"
